# Wochenplan 03

...zur Einheit vom 01. & 08.10.2020, Grundlagen (Teil 2)

## Lernziele

In der dritten Seminarwoche vertiefen wir Elemente der Programmiersprache R, die Sie bereits kennengelernt haben,  und betten sie in neue Zusammenhänge ein. Das Ziel ist es, das Verständnis von Funktionen und Objekten, von den verschiedenen Arten von Objekten in R sowie immer auch von der "Grammatik" dieser Sprache weiter zu schärfen. Zusätzlich werden in dieser Woche zwei neue Grundlagen eingeführt: Erstens die verschiedenen Arten von Daten, mit denen wir in R arbeiten: Zahlen, Text und logische Werte; zweitens einige Möglichkeiten, über bestimmte Funktionen systematisch Vektoren zu definieren. 

Zusammenfassend lassen sich damit folgende Seminarziele festhalten:

* Sie können mittels Argumenten eine Funktion spezifizieren und damit Einfluss auf die Details der Berechnung und der Ergebnisdarstellung nehmen.
* Sie können die drei bisher kennengelernten Objekttypen (einzelne Zahl, Vektor, und Matrix) kombinieren.
* Sie kennen die drei verschiedenen Datenarten von R:
  + Sie verstehen die Rolle von numerischen Daten,
  + Sie verstehen die Rolle von textförmigen Daten
  + Sie verstehen die Rolle von logischen Daten.
* Sie können Vektoren mittels der Funktionen ...
  + ... seq()
  + ... sowie rep() definieren
  + ... und diese auf alle drei Arten von Daten anwenden.


## Aufgaben

1. Der Vektor **v** besteht aus folgenden Zahlen: 1, 3, 7, 9, 22, 2, 8, 14, 20, 3, 7, 9, 11, und 13. Berechnen Sie auf drei verschiedenen Arten das arithmetische Mittel dieses Vektors.

2. Was macht das Argument 'trim' für die Funktion mean()? Wozu könnten Sie dieses Argument in einem sozialwissenschaftlichen Kontext nutzen? Spezifizieren Sie das Argument auf sinnvolle Weise, um das arithmetische Mittel des in Aufgabe 1 erstellten Vektors **v** zu berechnen!

3. Erstellen Sie vier verschiedene Vektoren mit je einer Länge von vier und verbinden Sie diese zu einer 4x4-Matrix. Die Funktion apply() erlaubt Ihnen, eine Funktionen wie z.B. mean() oder var() auf diese Matrix anzuwenden. Nur wie genau? Sehen Sie sich die Hilfe zu apply() an, probieren Sie die Funktion aus und versuchen Sie zu verstehen, wie sie genau funktioniert. Erläutern Sie apply() dann in eigenen Worten und mit Hilfe der von Ihnen erzeugten 4x4-Matrix! 

4. Erstellen Sie je einen Vektor mit numerischen Daten, textförmigen Daten und logischen Daten. Die Funktionen as.numeric(), as.character() und as.logical() lassen Sie eine Datenarten in eine andere "zwingen" bzw. als eine andere Datenart interpretieren. Wann funktioniert dies? Und wo sind die Grenzen dieses "Zwingens"?

5. Definieren Sie folgende Vektoren mittels der Funktionen seq() und rep():
  + Vektor 5a: 1 2 3 4 5 6 7 8 9 10
  + Vektor 5b: 1 1 1 2 2 2 3 3 3
  + Vektor 5c: Die Zahlen des Vektors b als ausgeschriebene Wörter
  + Vektor 5d: 1 4 7 10 13
  + Vektor 5e: 1 1 1 1 2 3 4 5
  
  
Arbeiten Sie für die Falllösung wiederum mit R Markdown und generieren Sie sich ein PDF Ihrer Lösungen. Beschriften Sie Ihr Dokument mit Fallloesung03_NameVorname.pdf und geben das Dokument via OLAT bis Mittwochmittag ab (07.10.2020, 12:00).
