# Sozialwissenschaftliche Datenanalyse mit R – Wochenplan 05 (15.– 22.10.2020)

## Lernziele

Ihre zentrale Aufgabe für die vergangene Woche bestand darin, R zu nutzen, um selbstständig "statistisch sinnvolle" Daten zu erzeugen und mit diesen zu arbeiten. Dazu haben wir zusätzlich zu den Funktionen 'seq()' und 'rep()' erstmals mit Zufallsvariablen gearbeitet, mit 'cor()' eine erste bivariate statistische Funktion eingesetzt sowie Streudiagramme und Histogramme erstellt. 

In der kommenden Arbeitswoche geht es nun darum, zwei neue Aspekte der Arbeit mit R kennenzulernen und einzuüben: das Zugreifen auf einzelne Elemente und Teile von Datenobjekten (Indizieren und Subsetting) und die Kontrolle von längeren Befehlsabläufen. Ausserdem werden wir mit Dataframes eine wichtige Art von Datenstrukturen in R einführen.

Folgende Lernziele lassen sich festhalten:

* Sie verstehen, was ein Dataframe in R ist und können die Unterschiede zu einer Matrix benennen.

* Sie können gezielt auf einzelne Teile eines Datenobjekts zugreifen und kennen verschiedene Wege, das zu tun.

* Sie verstehen, wie eine for-Schleife funktioniert und können einfache Varianten davon selbst erstellen.

* Sie beginnen in der Arbeit mit R gezielt Funktionen zur Abfrage von Attributen von Objekten zu nutzen.


## Aufgaben

1. Erzeugen Sie ein Dataframe, das aus fünf Variablen besteht und 100 Fälle umfasst. Nutzen Sie dazu die verschiedenen Funktionen, die wir in den letzten beiden Wochen kennengelernt haben (Zufallsvariablen, rep(), seq() ...). Probieren Sie ebenfalls, dass die fünfte Variablen dem Character Datenformat entspricht. Überlegen Sie sich einen sozialwissenschaftlichen Kontext für dieses Dataframe und benennen Sie die Variablen dementsprechend.

2. Wenden Sie die Funktionen 'dim()', 'names()', 'str()', 'class()' und 'typeof()' auf Ihr Dataframe an. Was sagen Ihnen diese Funktionen jeweils? Welcher Output dieser Funktionen leuchtet Ihnen ein, welcher weniger?

3. Schreiben Sie eine for-Schleife, die Ihnen für die vier numerischen Spalte Ihres Dataframes den Mittelwert berechnet. 

4. Überprüfen Sie Ihre Ergebnisse, indem Sie die Berechnung des Mittelwerts "händisch" für jede Spalte einzeln durchführen (nutzen Sie dazu Indizierung/Subsetting mittels eckiger Klammern).

5. Definieren Sie als eine erste Variante eine logische Bedingung, die Ihnen erlaubt, Ihr Dataframe anhand der Character-Variable in ungefähr zwei Gruppen zu teilen. Teilen Sie dann als zweite Variante Ihren Datensatz anhand einer anderen logischen Bedingung mit einer Ihrer numerischen Variablen in zwei Gruppen.

6. Berechnen Sie bei einer der beiden Varianten aus Aufgabe 6 dann noch einmal die Mittelwerte pro Spalte, aber getrennt für diese beiden Gruppen. 

&nbsp;

Arbeiten Sie für die Falllösung wiederum mit R Markdown und generieren Sie sich ein PDF Ihrer Lösungen. Beschriften Sie Ihr Dokument mit Fallloesung05_NameVorname.pdf und geben das Dokument via OLAT bis Mittwochmittag ab (21.10.2020, 12:00).

